// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require('@prisma/client')
import { hashPassword } from '../src/lib/auth'

const prisma = new PrismaClient()

async function main() {
  console.log('🎲 Seeding RPG Platform database...')

  // ─── Admin user ───────────────────────────────────────────
  const adminHash = await hashPassword('admin123')
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      username: 'admin',
      email: 'admin@rpgplatform.local',
      passwordHash: adminHash,
      role: 'ADMIN',
    },
  })
  console.log(`✓ Admin user: ${admin.username}`)

  // ─── Ordem Paranormal ─────────────────────────────────────
  const opSchema = {
    version: '2.0',
    attributes: [
      { id: 'agi', name: 'Agilidade', abbr: 'AGI', min: 1, max: 5, defaultValue: 1, category: 'base' },
      { id: 'int', name: 'Intelecto', abbr: 'INT', min: 1, max: 5, defaultValue: 1, category: 'base' },
      { id: 'pre', name: 'Presença', abbr: 'PRE', min: 1, max: 5, defaultValue: 1, category: 'base' },
      { id: 'for', name: 'Força', abbr: 'FOR', min: 1, max: 5, defaultValue: 1, category: 'base' },
      { id: 'vig', name: 'Vigor', abbr: 'VIG', min: 1, max: 5, defaultValue: 1, category: 'base' },
    ],
    skills: [
      { id: 'acrobacia', name: 'Acrobacia', linkedAttribute: 'agi' },
      { id: 'adestramento', name: 'Adestramento', linkedAttribute: 'pre' },
      { id: 'atletismo', name: 'Atletismo', linkedAttribute: 'for' },
      { id: 'atualidades', name: 'Atualidades', linkedAttribute: 'int' },
      { id: 'ciencias', name: 'Ciências', linkedAttribute: 'int' },
      { id: 'crime', name: 'Crime', linkedAttribute: 'agi' },
      { id: 'diplomacia', name: 'Diplomacia', linkedAttribute: 'pre' },
      { id: 'enganacao', name: 'Enganação', linkedAttribute: 'pre' },
      { id: 'fortitude', name: 'Fortitude', linkedAttribute: 'vig' },
      { id: 'furtividade', name: 'Furtividade', linkedAttribute: 'agi' },
      { id: 'iniciativa', name: 'Iniciativa', linkedAttribute: 'agi' },
      { id: 'intimidacao', name: 'Intimidação', linkedAttribute: 'pre' },
      { id: 'intuicao', name: 'Intuição', linkedAttribute: 'pre' },
      { id: 'investigacao', name: 'Investigação', linkedAttribute: 'int' },
      { id: 'luta', name: 'Luta', linkedAttribute: 'for' },
      { id: 'medicina', name: 'Medicina', linkedAttribute: 'int' },
      { id: 'ocultismo', name: 'Ocultismo', linkedAttribute: 'int' },
      { id: 'percepcao', name: 'Percepção', linkedAttribute: 'pre' },
      { id: 'pilotagem', name: 'Pilotagem', linkedAttribute: 'agi' },
      { id: 'pontaria', name: 'Pontaria', linkedAttribute: 'agi' },
      { id: 'profissao', name: 'Profissão', linkedAttribute: 'int' },
      { id: 'reflexos', name: 'Reflexos', linkedAttribute: 'agi' },
      { id: 'religiao', name: 'Religião', linkedAttribute: 'int' },
      { id: 'sobrevivencia', name: 'Sobrevivência', linkedAttribute: 'int' },
      { id: 'tatica', name: 'Tática', linkedAttribute: 'int' },
      { id: 'tecnologia', name: 'Tecnologia', linkedAttribute: 'int' },
      { id: 'vontade', name: 'Vontade', linkedAttribute: 'pre' },
    ],
    derivedStats: [
      { id: 'pv', name: 'Pontos de Vida', abbr: 'PV', formula: 'vig * 4 + 8', displayType: 'bar', color: '#ef4444' },
      { id: 'pe', name: 'Pontos de Esforço', abbr: 'PE', formula: 'pre + int + 2', displayType: 'bar', color: '#8b5cf6' },
      { id: 'san', name: 'Sanidade', abbr: 'SAN', formula: 'pre * 5', displayType: 'bar', color: '#06b6d4' },
    ],
    itemCategories: [
      {
        id: 'armas', name: 'Armas',
        fields: [
          { id: 'dano', name: 'Dano', type: 'text' },
          { id: 'alcance', name: 'Alcance', type: 'text' },
          { id: 'critico', name: 'Crítico', type: 'text' },
          { id: 'tipo', name: 'Tipo', type: 'select', options: ['Corpo a corpo', 'Arremesso', 'Tiro', 'Especial'] },
        ],
      },
      {
        id: 'protecao', name: 'Proteção',
        fields: [
          { id: 'defesa', name: 'Defesa', type: 'number' },
          { id: 'penalidade', name: 'Penalidade de Habilidade', type: 'number' },
          { id: 'tipo', name: 'Tipo', type: 'select', options: ['Leve', 'Pesada', 'Escudo'] },
        ],
      },
      {
        id: 'itens', name: 'Itens Gerais',
        fields: [
          { id: 'peso', name: 'Peso (kg)', type: 'number' },
          { id: 'descricao', name: 'Descrição', type: 'text' },
        ],
      },
    ],
    conditions: [
      { id: 'abalado', name: 'Abalado', description: 'Fica com medo facilmente.', iconName: 'brain' },
      { id: 'acuado', name: 'Acuado', description: '-2 em ataques, não pode usar reações.', iconName: 'shield-off' },
      { id: 'apavorado', name: 'Apavorado', description: 'Só pode fazer a ação Correr.', iconName: 'zap' },
      { id: 'caído', name: 'Caído', description: 'Deve gastar 5m para levantar.', iconName: 'arrow-down' },
      { id: 'cego', name: 'Cego', description: 'Não pode ver.', iconName: 'eye-off' },
      { id: 'lento', name: 'Lento', description: 'Deslocamento reduzido à metade.', iconName: 'footprints' },
      { id: 'ofuscado', name: 'Ofuscado', description: '-2 em ataques e Percepção.', iconName: 'sun' },
      { id: 'paralisado', name: 'Paralisado', description: 'Não pode agir ou se mover.', iconName: 'pause' },
      { id: 'pasmo', name: 'Pasmo', description: 'Não pode agir, mas pode se mover.', iconName: 'alert-circle' },
      { id: 'sangrando', name: 'Sangrando', description: 'Perde 1d6 PV no início de cada turno.', iconName: 'droplets' },
      { id: 'surdo', name: 'Surdo', description: 'Não pode ouvir.', iconName: 'volume-x' },
      { id: 'vulneravel', name: 'Vulnerável', description: 'Ataques contra você têm vantagem.', iconName: 'shield-off' },
    ],
    sheetSections: [
      { id: 'info', title: 'Informações', component: 'SheetInfo', order: 0 },
      { id: 'attributes', title: 'Atributos', component: 'SheetAttributes', order: 1 },
      { id: 'derived', title: 'PV / PE / Sanidade', component: 'SheetDerivedStats', order: 2 },
      { id: 'skills', title: 'Perícias', component: 'SheetSkills', order: 3 },
      { id: 'inventory', title: 'Inventário', component: 'SheetInventory', order: 4 },
      { id: 'spells', title: 'Rituais do Outro Mundo', component: 'SheetSpells', order: 5, collapsible: true },
      { id: 'notes', title: 'Anotações', component: 'SheetNotes', order: 6, collapsible: true },
    ],
  }

  const opData = {
    origins: [
      {
        id: 'amnésico',
        name: 'Amnésico',
        description: 'Você não sabe quem é, de onde veio ou o que fez antes de despertar em um lugar estranho. Tudo o que existe é o presente.',
        bonuses: { int: 1 },
        abilities: ['Identidade Fragmentada', 'Memória Fotográfica'],
        skills: ['investigacao', 'percepcao'],
      },
      {
        id: 'artista',
        name: 'Artista',
        description: 'Você se expressa através da arte — música, pintura, poesia — e encontrou no Outro Mundo uma inspiração que ninguém mais consegue compreender.',
        bonuses: { pre: 1 },
        abilities: ['Expressão do Outro Mundo', 'Criatividade Profana'],
        skills: ['enganacao', 'percepcao'],
      },
      {
        id: 'celebridade',
        name: 'Celebridade',
        description: 'Você é famoso. Atores, músicos, influenciadores digitais… e agora você enfrenta o Outro Mundo com milhares de seguidores assistindo.',
        bonuses: { pre: 1 },
        abilities: ['Fama', 'Figura Pública'],
        skills: ['enganacao', 'diplomacia'],
      },
      {
        id: 'científico',
        name: 'Científico',
        description: 'A ciência sempre foi sua âncora. Mas como explicar o inexplicável usando metodologia científica?',
        bonuses: { int: 1 },
        abilities: ['Pesquisador', 'Teoria em Campo'],
        skills: ['ciencias', 'medicina'],
      },
      {
        id: 'criminoso',
        name: 'Criminoso',
        description: 'Seja ladrão, hacker ou assassino — você viveu nas sombras e conhece os segredos que a sociedade prefere ignorar.',
        bonuses: { agi: 1 },
        abilities: ['Contatos do Submundo', 'Vida nas Sombras'],
        skills: ['crime', 'furtividade'],
      },
      {
        id: 'cultista',
        name: 'Cultista',
        description: 'Você pertenceu a um culto. Pode ter deixado, mas a marca que isso deixou vai além do psicológico.',
        bonuses: { pre: 1 },
        abilities: ['Rituais Proibidos', 'Fe Ferrenha'],
        skills: ['ocultismo', 'religiao'],
      },
      {
        id: 'esportista',
        name: 'Esportista',
        description: 'Disciplina, treino e superação são suas ferramentas. Seu corpo é uma máquina afinada para o desempenho máximo.',
        bonuses: { for: 1 },
        abilities: ['Condicionamento Físico', 'Superação'],
        skills: ['atletismo', 'acrobacia'],
      },
      {
        id: 'investigador',
        name: 'Investigador',
        description: 'Detetive, jornalista investigativo ou simplesmente curioso obsessivo — você não para até encontrar a verdade.',
        bonuses: { int: 1 },
        abilities: ['Farejador de Pistas', 'Memória Eidética'],
        skills: ['investigacao', 'intuicao'],
      },
      {
        id: 'médico',
        name: 'Médico',
        description: 'Você passou anos estudando o corpo humano. Agora descobre que existem coisas que a medicina nunca catalogou.',
        bonuses: { int: 1 },
        abilities: ['Tratamento Emergencial', 'Diagnóstico Rápido'],
        skills: ['medicina', 'ciencias'],
      },
      {
        id: 'militar',
        name: 'Militar',
        description: 'Treinado para situações de combate extremo, você segue protocolos mesmo quando o protocolo se chama "matar um monstro dimensional".',
        bonuses: { for: 1 },
        abilities: ['Treinamento Tático', 'Disciplina Militar'],
        skills: ['tatica', 'atletismo'],
      },
      {
        id: 'ocultista',
        name: 'Ocultista',
        description: 'Você sempre soube que havia mais além do véu da realidade. Agora você tem provas.',
        bonuses: { int: 1 },
        abilities: ['Conhecimento Proibido', 'Sentido Paranormal'],
        skills: ['ocultismo', 'religiao'],
      },
      {
        id: 'policial',
        name: 'Policial',
        description: 'Proteger e servir. Mas quando o que ameaça a cidade não é humano, como você serve?',
        bonuses: { pre: 1 },
        abilities: ['Autoridade', 'Rede de Informações'],
        skills: ['investigacao', 'luta'],
      },
      {
        id: 'religioso',
        name: 'Religioso',
        description: 'Sua fé sempre foi inabalável. O Outro Mundo não abalou sua crença — pelo contrário, confirmou que existem forças além da compreensão humana.',
        bonuses: { pre: 1 },
        abilities: ['Fé Inabalável', 'Proteção Divina'],
        skills: ['religiao', 'vontade'],
      },
      {
        id: 'soldado',
        name: 'Soldado',
        description: 'Diferente do militar formal, você combateu em zonas de guerra, grupos paramilitares ou como mercenário.',
        bonuses: { for: 1 },
        abilities: ['Veterano de Guerra', 'Sobrevivência Extrema'],
        skills: ['tatica', 'sobrevivencia'],
      },
      {
        id: 'tecnólogo',
        name: 'Tecnólogo',
        description: 'Hacker, engenheiro, programador — você entende sistemas e sabe que o Outro Mundo tem suas próprias conexões de rede.',
        bonuses: { int: 1 },
        abilities: ['Interface Neural', 'Análise de Sistemas'],
        skills: ['tecnologia', 'ciencias'],
      },
      {
        id: 'trambiqueiro',
        name: 'Trambiqueiro',
        description: 'Você sempre se virou com o que tinha, usando lábia, esperteza e uma boa dose de sorte.',
        bonuses: { pre: 1 },
        abilities: ['Lábia', 'Sempre um Plano B'],
        skills: ['enganacao', 'crime'],
      },
    ],
    spells: [
      {
        id: 'detectar_presenca',
        name: 'Detectar Presença',
        description: 'Você sente a presença de entidades do Outro Mundo próximas.',
        school: 'Percepção',
        level: 1,
        cost: '1 PE',
        range: '9 metros',
        target: 'Área',
        duration: 'Instantânea',
        effect: 'Você detecta a localização de qualquer entidade do Outro Mundo em alcance.',
        tags: ['percepção', 'paranormal'],
      },
      {
        id: 'luz_amaldicoada',
        name: 'Luz Amaldiçoada',
        description: 'Uma luz profana que revela o que está oculto no Outro Mundo.',
        school: 'Revelação',
        level: 1,
        cost: '1 PE',
        range: '6 metros',
        target: '1 criatura',
        duration: 'Cena',
        effect: 'Ilumina criaturas invisíveis e objetos do Outro Mundo na área.',
        tags: ['revelação', 'luz'],
      },
      {
        id: 'sussurros_proibidos',
        name: 'Sussurros Proibidos',
        description: 'Você extrai informações de entidades que normalmente não falariam.',
        school: 'Comunicação',
        level: 2,
        cost: '2 PE',
        range: 'Pessoal',
        target: '1 entidade',
        duration: 'Instantânea',
        effect: 'Forçar uma entidade a responder três perguntas de sim/não.',
        tags: ['comunicação', 'mental'],
      },
      {
        id: 'barreira_protegida',
        name: 'Barreira Protegida',
        description: 'Uma proteção temporária contra as forças do Outro Mundo.',
        school: 'Proteção',
        level: 2,
        cost: '2 PE',
        range: 'Pessoal',
        target: 'Você',
        duration: 'Cena',
        effect: 'Você ganha +2 de defesa contra ataques sobrenaturais.',
        tags: ['proteção', 'defesa'],
      },
      {
        id: 'transe_medianico',
        name: 'Transe Mediânico',
        description: 'Você entra em contato direto com o Outro Mundo, recebendo visões.',
        school: 'Visão',
        level: 3,
        cost: '3 PE + 1d6 de SAN',
        range: 'Pessoal',
        target: 'Você',
        duration: 'Minutos',
        effect: 'Você recebe uma visão profética sobre o passado, presente ou futuro relacionado a uma pergunta.',
        tags: ['visão', 'poder', 'risco'],
      },
      {
        id: 'banimento',
        name: 'Banimento',
        description: 'Você força uma entidade de volta ao Outro Mundo.',
        school: 'Expulsão',
        level: 4,
        cost: '4 PE',
        range: '9 metros',
        target: '1 entidade',
        duration: 'Instantânea',
        effect: 'Você tenta banir uma entidade. Teste de Ocultismo vs. Will da entidade. Se bem-sucedido, ela é expulsa.',
        tags: ['expulsão', 'poder'],
      },
    ],
    weapons: [
      {
        id: 'faca',
        name: 'Faca',
        type: 'Corpo a corpo',
        damage: '1d4+FOR',
        range: 'Curto (arremesso)',
        crit: '20/x2',
        weight: 0.5,
        properties: ['Leve', 'Arremesso'],
        description: 'Uma faca comum, eficaz a curta distância.',
      },
      {
        id: 'cacetete',
        name: 'Cacetete',
        type: 'Corpo a corpo',
        damage: '1d6+FOR',
        range: 'Corpo a corpo',
        crit: '20/x2',
        weight: 1.5,
        properties: [],
        description: 'Um cacetete simples de madeira ou metal.',
      },
      {
        id: 'pistola_9mm',
        name: 'Pistola 9mm',
        type: 'Tiro',
        damage: '1d6',
        range: '20m / 40m',
        crit: '20/x2',
        weight: 0.9,
        properties: ['Munição (clip, 15)'],
        description: 'Pistola semiautomática padrão.',
      },
      {
        id: 'espingarda',
        name: 'Espingarda',
        type: 'Tiro',
        damage: '2d6',
        range: '9m / 18m',
        crit: '20/x2',
        weight: 3.5,
        properties: ['Munição (2 cartucho)', 'Dispersão'],
        description: 'Arma devastadora a curta distância.',
      },
      {
        id: 'rifle',
        name: 'Rifle',
        type: 'Tiro',
        damage: '1d8+1',
        range: '60m / 180m',
        crit: '19-20/x2',
        weight: 4.0,
        properties: ['Munição (clip, 5)', 'Pesado'],
        description: 'Rifle de caça ou assalto levemente modificado.',
      },
      {
        id: 'machado',
        name: 'Machado',
        type: 'Corpo a corpo',
        damage: '1d8+FOR',
        range: 'Corpo a corpo',
        crit: '20/x3',
        weight: 2.5,
        properties: [],
        description: 'Machado de lenhador adaptado para combate.',
      },
    ],
  }

  const ordemParanormal = await prisma.rpgSystem.upsert({
    where: { slug: 'ordem-paranormal' },
    update: { schema: opSchema as object, data: opData as object, isPublished: true },
    create: {
      name: 'Ordem Paranormal',
      slug: 'ordem-paranormal',
      description: 'Jogo de RPG brasileiro de horror paranormal. Investigue o Outro Mundo e tente manter sua sanidade.',
      version: '2.0',
      schema: opSchema as object,
      data: opData as object,
      isPublished: true,
    },
  })
  console.log(`✓ System: ${ordemParanormal.name}`)

  // ─── D&D 5e (basic) ───────────────────────────────────────
  const dnd5eSchema = {
    version: '5e',
    attributes: [
      { id: 'str', name: 'Força', abbr: 'STR', min: 1, max: 30, defaultValue: 10, category: 'physical' },
      { id: 'dex', name: 'Destreza', abbr: 'DEX', min: 1, max: 30, defaultValue: 10, category: 'physical' },
      { id: 'con', name: 'Constituição', abbr: 'CON', min: 1, max: 30, defaultValue: 10, category: 'physical' },
      { id: 'int', name: 'Inteligência', abbr: 'INT', min: 1, max: 30, defaultValue: 10, category: 'mental' },
      { id: 'wis', name: 'Sabedoria', abbr: 'WIS', min: 1, max: 30, defaultValue: 10, category: 'mental' },
      { id: 'cha', name: 'Carisma', abbr: 'CHA', min: 1, max: 30, defaultValue: 10, category: 'social' },
    ],
    skills: [
      { id: 'athletics', name: 'Atletismo', linkedAttribute: 'str' },
      { id: 'acrobatics', name: 'Acrobacia', linkedAttribute: 'dex' },
      { id: 'sleight_of_hand', name: 'Prestidigitação', linkedAttribute: 'dex' },
      { id: 'stealth', name: 'Furtividade', linkedAttribute: 'dex' },
      { id: 'arcana', name: 'Arcanismo', linkedAttribute: 'int' },
      { id: 'history', name: 'História', linkedAttribute: 'int' },
      { id: 'investigation', name: 'Investigação', linkedAttribute: 'int' },
      { id: 'nature', name: 'Natureza', linkedAttribute: 'int' },
      { id: 'religion', name: 'Religião', linkedAttribute: 'int' },
      { id: 'animal_handling', name: 'Adestrar Animais', linkedAttribute: 'wis' },
      { id: 'insight', name: 'Intuição', linkedAttribute: 'wis' },
      { id: 'medicine', name: 'Medicina', linkedAttribute: 'wis' },
      { id: 'perception', name: 'Percepção', linkedAttribute: 'wis' },
      { id: 'survival', name: 'Sobrevivência', linkedAttribute: 'wis' },
      { id: 'deception', name: 'Enganação', linkedAttribute: 'cha' },
      { id: 'intimidation', name: 'Intimidação', linkedAttribute: 'cha' },
      { id: 'performance', name: 'Atuação', linkedAttribute: 'cha' },
      { id: 'persuasion', name: 'Persuasão', linkedAttribute: 'cha' },
    ],
    derivedStats: [
      { id: 'hp', name: 'Pontos de Vida', abbr: 'PV', formula: 'con', displayType: 'bar', color: '#ef4444' },
      { id: 'ac', name: 'Classe de Armadura', abbr: 'CA', formula: '10', displayType: 'number', color: '#94a3b8' },
    ],
    itemCategories: [
      { id: 'weapons', name: 'Armas', fields: [{ id: 'damage', name: 'Dano', type: 'text' }, { id: 'range', name: 'Alcance', type: 'text' }] },
      { id: 'armor', name: 'Armadura', fields: [{ id: 'ac', name: 'CA', type: 'number' }] },
      { id: 'items', name: 'Itens', fields: [{ id: 'weight', name: 'Peso (lb)', type: 'number' }] },
    ],
    conditions: [],
    sheetSections: [
      { id: 'info', title: 'Informações', component: 'SheetInfo', order: 0 },
      { id: 'attributes', title: 'Atributos', component: 'SheetAttributes', order: 1 },
      { id: 'derived', title: 'Status', component: 'SheetDerivedStats', order: 2 },
      { id: 'skills', title: 'Perícias', component: 'SheetSkills', order: 3 },
      { id: 'inventory', title: 'Inventário', component: 'SheetInventory', order: 4 },
      { id: 'spells', title: 'Magias', component: 'SheetSpells', order: 5, collapsible: true },
      { id: 'notes', title: 'Notas', component: 'SheetNotes', order: 6, collapsible: true },
    ],
  }

  const dnd5e = await prisma.rpgSystem.upsert({
    where: { slug: 'dnd-5e' },
    update: { schema: dnd5eSchema as object, isPublished: true },
    create: {
      name: 'Dungeons & Dragons 5e',
      slug: 'dnd-5e',
      description: 'O sistema de RPG mais popular do mundo. Aventuras épicas em mundos de fantasia.',
      version: '5e',
      schema: dnd5eSchema as object,
      data: {} as object,
      isPublished: true,
    },
  })
  console.log(`✓ System: ${dnd5e.name}`)

  console.log('\n✅ Seed concluído!')
  console.log('   Admin: admin / admin123')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
